# Generated by Django 4.2 on 2025-03-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailings",
                to="mailings.recipient",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("completed", "Завершена"),
                    ("disabled", "Отключена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
